<font size='4'>**In this file we introduce the luminosity distance expansions in terms of the redshift variables z, y, log(1+z), plus Pade polynomials 22 and 21 and the Eis series.**


<font size='4'>**In the second part we run the minimizing results**

<font size='5'><span style="color:red">To do:

1. Change z_series etc in order to include Omega_k and w
2. Change z distribution to something like Pantheon+
3. Make a spline of Eis cosmology integral



</font>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import astropy
from astropy.cosmology import Planck15
import astropy.cosmology as cosmo
import astropy.units as u
from scipy.optimize import minimize

In [2]:
H0 =  73.8
Om = 0.3
Ok = 0.0
w = -1.0

my_cosmo = cosmo.wCDM(H0=H0, Om0=Om, Ode0=1.0-Om-Ok)

zs = np.linspace(0.001, 1.5, 100)
zs = zs[1:] # We don't want z = 0
dls_true = my_cosmo.luminosity_distance(zs).to(u.Mpc).value
ys = zs/(1+zs)

In [3]:
def redshift_expansion(z, H0, a0, a1, a2, a3, a4, a5, order):
    if order == 0:
        return 300000 * z / H0 * (a0)
    elif order == 1:
        return 300000 * z / H0 * (a0 + a1*z)
    elif order == 2:
        return 300000 * z / H0 * (a0 + a1*z + a2 * z**2.0)
    elif order == 3:
        return 300000 * z / H0 * (a0 + a1*z + a2 * z**2.0 + a3 * z**3.0)
    elif order == 4:
        return 300000 * z / H0 * (a0 + a1*z + a2 * z**2.0 + a3 * z**3.0 + a4 * z**4.0)
    elif order == 5:
        return 300000 * z / H0 * (a0 + a1*z + a2 * z**2.0 + a3 * z**3.0 + a4 * z**4.0 + a5 * z**5.0)

In [4]:
def to_cosmographic(H0, Om, Ok, w):
    q0 = 1.0/2.0 *(1.0-Ok-3.0*(-1.0+Om+Ok)*w)
    j0 = 1.0/2.0 * (2.0 * Om + (1.0 - Om - Ok)*(2+9*w*(1+w)))
    s0 = 1.0/4.0 * (2*(7-Ok)*(Ok-1.0)+3*(5*Ok-27)*(1-Om-Ok)*w+9*(1-Om-Ok)*(-16+4*Ok+3*Om)*w**2 + 27.0*(-3.0+Ok+Om)*(1-Ok-Om)*w**3)
    #l0 = ( 243.0 / 2.0 - 405.0 / 2.0 * Ok - 405.0 / 2.0 * Om + 81.0 * Ok**2.0 + 162.0 * Ok * Om + 81.0 * Om**2.0 ) * w**4.0 + ( 729.0 / 4.0 * Ok**2.0 + 1377.0 / 4.0 * Ok * Om + 162.0 * Om**2.0 -999.0 / 2.0 * Ok - 1917.0 / 4.0 * Om + 1269.0 / 4.0 ) * w**3.0  + ( 603.0 / 2.0 - 891.0 / 2.0 * Ok - 396.0 * Om + 144.0 * Ok**2.0 + 477.0 / 2.0 * Ok * Om + 189.0 / 2.0 * Om**2.0 ) * w**2.0 + ( 189.0 / 4.0 * Ok**2.0 + 189.0 / 4.0 * Ok * Om - 339.0 / 2.0 * Ok + 489.0 / 4.0 - 489.0 / 4.0 * Om) * w  + 35.0 / 2.0 + 11.0 / 2.0 * Ok**2.0 - 23.0 * Ok 
    #m0 = ( - 4131.0 / 4.0 * Ok**2.0 - 4131.0 / 2.0 * Ok * Om - 4131.0 / 4.0 * Om**2.0 + 3645.0 / 2.0 * Ok + 3645.0 / 2.0 * Om - 3645.0 / 4.0 + 243.0 / 2.0 * Ok**3.0 + 729.0 / 2.0 * Ok**2.0 * Om + 729.0 / 2.0 * Ok * Om**2.0 + 243.0 / 2.0 * Om**3.0 ) * w**5.0  + ( 23409.0 / 4.0 * Om - 25515.0 / 8.0 * Ok**2.0 - 25353.0 / 8.0 + 48357.0 / 8.0 * Ok + 2511.0 / 8.0 * Ok**3.0 + 243.0 * Om**3.0 + 3483.0 / 4.0 * Ok**2.0 * Om + 6399.0 / 8.0 * Ok * Om**2.0 - 23409.0 / 8.0 * Om**2.0 - 12231.0 / 2.0 * Ok * Om ) * w**4.0 + ( 57267.0 / 8.0 * Om - 30321.0 / 8.0 * Ok**2.0 - 34587.0 / 8.0 + 62451.0 / 8.0 * Ok + 2457.0 / 8.0 * Ok**3.0 + 567.0 / 4.0 * Om**3.0 + 5967.0 / 8.0 * Ok**2.0 * Om + 1161.0 / 2.0 * Ok * Om**2.0 - 11907.0 / 4.0 * Om**2.0  - 27027.0 / 4.0 * Ok * Om ) * w**3.0  + ( 1143.0 / 8.0 * Ok**3.0 + 261.0 * Ok**2.0 * Om - 17199.0 / 8.0 * Ok**2.0 + 945.0 / 8.0 * Ok * Om**2.0 - 6579.0 / 2.0 * Ok * Om + 39069.0 / 8.0 * Ok - 23013.0 / 8.0 + 4041.0 * Om - 9315.0 / 8.0 * Om**2.0 ) * w**2  + ( 255.0 / 8.0 * Ok**3.0 + 255.0 / 8.0 * Ok**2.0 * Om - 4629.0 / 8.0 * Ok**2.0 - 2187.0 / 4.0 * Ok * Om + 11781.0 / 8.0 * Ok - 7407.0 / 8.0 + 7407.0 / 8.0 * Om ) * w - 237.0 / 4.0 * Ok**2.0 + 681.0 / 4.0 * Ok - 455.0 / 4.0 + 11.0 / 4.0 * Ok**3.0   
    #must be checked
    return H0, q0, j0, s0

In [5]:
def z_series(z, H0, q0, j0, s0):

    a0 = 1.0
    a1 = 1.0/2.0 - q0/2.0
    a2 = -1.0/6.0 - j0/6.0 + q0/6.0 + q0**2.0 / 2.0
    a3 = 1.0/12.0 + 5 * j0 / 24.0 - q0/12.0 + 5.0*j0*q0/12.0  -5.0 * q0**2.0 / 8.0  -5.0 * q0**3.0 / 8.0 + s0/24.0
    #a4 = -1.0/20.0 - 9*j0/40.0 +j0**2/12.0 -l0/120.0 +q0/20.0 \
         # -11*j0*q0/12.0 +27*q0**2/40.0 -7*j0*q0**2/8.0 \
         # + 11*q0**3/8.0+7*q0**4/8-11*s0/120-q0*s0/8.0
    #a5 = 1.0/30.0 + 7*j0/30.0 - 19.0*j0**2/72 + 19.0*l0/720.0 \
         # +m0/720-q0/30.0+13*j0*q0/9-7*j0**2*q0/18.0+7*l0*q0/240.0 \
         # -7*q0**2.0/10.0+133.0*j0*q0**2.0/48.0-13.0*q0**3.0/6.0 \
         # +7.0*j0*q0**3.0/4.0-133.0*q0**4.0/48.0-21.0*q0**5.0/16.0  \
         # +13.0*s0/90.0-7.0*j0*s0/144.0+19.0*q0*s0/48.0+7*q0**2.0*s0/24

    #return redshift_expansion(z, H0, a0, a1, a2, a3, order)
    return 300000 * z / H0 * (a0 + a1*z + a2 * z**2.0 + a3 * z**3.0)


def chi_square_z(theta, z, data):
    H0, q0, j0, s0 = theta
    diff = z_series(z, H0, q0, j0, s0) - data
    return np.sum(diff*diff)

In [6]:
def y_series(y, H0, q0, j0, s0):

    a0 = 1.0
    a1 = -1/2*(q0-3)
    a2 = 1/6 * (12-5*q0+3*q0**2-j0)
    a3 = 1/24 * (50 - 7*j0 -26*q0+10*q0*j0+21*q0**2-15*q0**3+s0)

    #return redshift_expansion(z, H0, a0, a1, a2, a3, order)
    return 300000 * y / H0 * (a0 + a1*y + a2 * y**2.0 + a3 * y**3.0)


def chi_square_y(theta, y, data):
    H0, q0, j0, s0  = theta
    diff = y_series(y, H0, q0, j0, s0) - data
    return np.sum(diff*diff)

In [7]:
def log_series(log1z, H0, q0, j0, s0):

    a0p = 1.0
    a1p = 1 -1/2*q0
    a2p = 1/6 * (3-2*q0+3*q0**2-j0)
    a3p =  1/6 +(1/8)*(-q0 + q0**2 -5*q0**3) +(5/12)*q0*j0 + 1/24*(-j0 + s0)

    #return redshift_expansion(z, H0, a0, a1, a2, a3, order)
    return 300000 * log1z / H0 * (a0p + a1p*log1z + a2p * log1z**2.0 + a3p * log1z**3.0)


def chi_square_log(theta, log1z, data):
    H0, q0, j0, s0  = theta
    diff = log_series(log1z, H0, q0, j0, s0) - data
    return np.sum(diff*diff)

In [8]:
def dLpade22(z,H0, q0, j0, s0):
    numerator = (6 *z* (10 + 9 * z - 6 * (q0**3) * z  
                        +s0 * z - 2 * (q0**2) * (3 + 7 * z) - q0 * (16 + 19 * z) + j0 * (4 + (9 + 6 * q0) * z)))
    denominator = (60 + 24 * z + 6 * s0 * z - 2 * z**2+ 4 * (j0**2) * z**2 - 9 * (q0**4) * z**2 - 3 * s0 * z**2 
                   + 6 * q0**3 * z * (-9 + 4 * z)  + q0**2 * (-36 - 114 * z + 19 * z**2) + j0 * (24 + 6 * (7 + 8 * q0) * z 
                   + (-7 - 23 * q0 + 6 * q0**2) * z**2) + q0 * (-96 - 36 * z + (4 + 3 * s0) * z**2))

    Pz_value =  (300000/H0)*(numerator / (denominator ) )
    return Pz_value

def lkl_pade22(pars,z,data):
    y=data
    x=dLpade22(z,*pars)
    return np.sum((y-x)**2)

In [9]:
def dLpade21(z,H0, q0, j0):
    numerator = z * (6 * (-1 + q0) + (-5 -2*j0 +q0 * (8 + 3*q0))*z)
    denominator = -2 * (3 + z + j0*z) + 2*q0 * (3 + z + 3*q0*z)

    P2z_value =  (300000/H0)*(numerator / (denominator ) )
    return P2z_value

def lkl_pade21(pars,z,data):
    y=data
    x=dLpade21(z,*pars)
    return np.sum((y-x)**2)

In [10]:
from scipy import integrate
c=300000
q0=-0.55
j0=1
s0=-0.35
E0=1
E1=1+q0
E2=-q0**2+j0
E3=3*q0**2+3*q0*3-j0*(4*q0+3)-s0

zlow=0.03
zmid=0.5
zhigh= 6
def dL_EIS41(z,E0,E1,E2,E3,H0):
    dL=np.full(z.shape,np.nan)
    def func(z,E0,E1,E2,E3):
        if z_val<=zlow:
            y=1/(E0+E1*z)
        elif zlow<z_val<=zmid:
            y=1/(E0+E1*z+(E2*z**2)/2)
        elif zmid<z_val<=zhigh:
            y=1/(E0+E1*z+(E2*z**2)/2+(E3*z**3)/6)
        else:
            y = 1 / (E0 + E1 * z + (E2 * z**2) / 2 + (E3 * z**3) / 6+ (E4 * z**4) / 24)
        return y

    for  i,z_val in  np.ndenumerate(z):
        #print(z_val,integrate.quad(func,0,z_val,args=(E0,E1,E2,E3)))
        dL[i]=(1+z_val)*integrate.quad(func,0,z_val,args=(E0,E1,E2,E3),limit=100)[0]
    return (c/H0)*dL



def lkl_eis41(pars,z,y):

    x=dL_EIS41(z,*pars)
    return np.sum((y-x)**2)


def lkl_eis31(pars,z,y):

    x=dL_EIS31(z,*pars)
    return np.sum((y-x)**2)

def to_statefinders1(theta):
    H0_pop=theta[-1]
    theta=theta[:-1]
    E0=theta[0]
    E1=theta[1]
    E2=theta[2]
    q0=E1 - 1
    j0=E1**2 - 2*E1 + E2 + 1
    theta_final=[q0,j0]
    try:
            E3=theta[3]
            s0=-4*E1**3 + 12*E1**2 - 4*E1*E2 - 3*E1 + E2 - E3 - 5
            theta_final.append(s0)
    except:
        pass
    theta_final.append(H0_pop)
    return theta_final

q0=-0.55
j0=1
s0=-0.35
E0=1
E1=1+q0
E2=-q0**2+j0
E3=3*q0**2+3*q0**3-j0*(4*q0+3)-s0
prior1=[E0,E1,E2,E3,75]
#MLE1 = minimize(lkl_eis41,prior1, method = 'Powell', tol=10**-14, args=(zs, dls_true), options={'maxiter':150000})
MLE2 = minimize(lkl_eis41,prior1, method = 'Powell', tol=10**-12, args=(zs, dls_true), options={'maxiter':150000})

#MLE3 = minimize(lkl_eis41,prior1, method = 'trust-constr', tol=10**-14, args=(zs, dls_true), options={'maxiter':150000})
#prior2=[E0,E1,E2,75]
#MLE2 = minimize(lkl_eis31,prior2, method = 'Powell',args=(zs, dls_true), tol=10**-12,  options={'maxiter':150000})
print(MLE2)

/tmp/ipykernel_8407/2876868533.py:29: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  dL[i]=(1+z_val)*integrate.quad(func,0,z_val,args=(E0,E1,E2,E3),limit=100)[0]
/tmp/ipykernel_8407/2876868533.py:29: IntegrationWarning: Extremely bad integrand behavior occurs at some points of the
  integration interval.
  dL[i]=(1+z_val)*integrate.quad(func,0,z_val,args=(E0,E1,E2,E3),limit=100)[0]
/tmp/ipykernel_8407/2876868533.py:29: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  dL[i]=(1+z_val)*integrate.quad(func,0,z_val,args=(E0,E1,E2,E3),limit=100)[0]


 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 17.390465862845243
       x: [ 9.821e-01  4.534e-01  6.737e-01 -2.421e-01  7.507e+01]
     nit: 20
   direc: [[ 6.947e-06 -1.253e-03 ... -6.688e-03  8.816e-03]
           [ 1.290e-06  4.497e-06 ... -1.834e-05 -1.555e-04]
           ...
           [ 1.398e-03  5.333e-03 ... -1.434e-02 -2.086e-01]
           [ 2.259e-05 -4.700e-04 ... -2.992e-03  1.900e-03]]
    nfev: 2791


In [11]:
dL_EIS41(np.array([1.2]),E0,E1,E2,E3,H0)
print(to_statefinders1(MLE2.x))
MLE2.x
E3=3*q0**2+3*q0**3-j0*(4*q0+3)-s0
E3



eis_res41=to_statefinders1(MLE2.x)
#eis_res42=to_statefinders1(MLE3.x)
#eis_res3=to_statefinders1(MLE2.x)

print(eis_res41)
[E0,E1,E2,E3,73.6]
zs

[-0.5465791938373383, 0.9724784429506348, -4.57218947780826, 75.06722422104066]
[-0.5465791938373383, 0.9724784429506348, -4.57218947780826, 75.06722422104066]


array([0.01614141, 0.03128283, 0.04642424, 0.06156566, 0.07670707,
       0.09184848, 0.1069899 , 0.12213131, 0.13727273, 0.15241414,
       0.16755556, 0.18269697, 0.19783838, 0.2129798 , 0.22812121,
       0.24326263, 0.25840404, 0.27354545, 0.28868687, 0.30382828,
       0.3189697 , 0.33411111, 0.34925253, 0.36439394, 0.37953535,
       0.39467677, 0.40981818, 0.4249596 , 0.44010101, 0.45524242,
       0.47038384, 0.48552525, 0.50066667, 0.51580808, 0.53094949,
       0.54609091, 0.56123232, 0.57637374, 0.59151515, 0.60665657,
       0.62179798, 0.63693939, 0.65208081, 0.66722222, 0.68236364,
       0.69750505, 0.71264646, 0.72778788, 0.74292929, 0.75807071,
       0.77321212, 0.78835354, 0.80349495, 0.81863636, 0.83377778,
       0.84891919, 0.86406061, 0.87920202, 0.89434343, 0.90948485,
       0.92462626, 0.93976768, 0.95490909, 0.97005051, 0.98519192,
       1.00033333, 1.01547475, 1.03061616, 1.04575758, 1.06089899,
       1.0760404 , 1.09118182, 1.10632323, 1.12146465, 1.13660

**Minimizing results**

In [12]:
btheta=((65,75),(-2,2), (-5,5), (-5,5))

In [13]:
results_z = minimize(chi_square_z, [70, 0.30, 0.70, 1], bounds=btheta,args=(zs, dls_true), method='L-BFGS-B', options={'maxiter':20000})
print(results_z)

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 18.63599987936511
        x: [ 7.366e+01 -5.232e-01  9.130e-01  2.421e-01]
      nit: 143
      jac: [ 4.163e+00  2.049e+01  6.009e+01 -2.031e+01]
     nfev: 955
     njev: 191
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>


In [14]:
results_y = minimize(chi_square_y, [70, 0.30, 0.70, 1], args=(ys, dls_true), bounds=btheta, method='L-BFGS-B', options={'maxiter':20000})
print(results_y)

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 1714241.9974492204
        x: [ 7.500e+01 -3.059e-01 -5.000e+00  5.000e+00]
      nit: 27
      jac: [-1.903e+05 -4.889e-01  1.461e+05 -1.916e+04]
     nfev: 200
     njev: 40
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>


In [15]:
log1zs = np.log(1+zs)
results_log = minimize(chi_square_log, [70, 0.30, 0.70, 1], args=(log1zs, dls_true), bounds=btheta, method='L-BFGS-B', options={'maxiter':20000})
print(results_log)

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 8.70387982334372
        x: [ 7.411e+01 -6.155e-01  1.719e+00  4.337e+00]
      nit: 79
      jac: [ 7.839e+00  2.324e+02  4.959e+01 -4.019e+00]
     nfev: 560
     njev: 112
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>


In [16]:
prior=[70,-0.55,1,-0.35]
results_pade22 = minimize(lkl_pade22,prior,args=(zs,dls_true), method = 'Powell', tol=10**-13,  options={'maxiter':150000})
print(results_pade22)

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 9.501241891853502
       x: [ 7.415e+01 -6.262e-01  1.838e+00  5.334e+00]
     nit: 72
   direc: [[ 1.801e-03 -3.204e-04  2.521e-03  1.513e-02]
           [-1.724e-04  2.538e-05 -1.954e-04 -1.184e-03]
           [ 8.705e-03 -1.350e-03  1.044e-02  6.274e-02]
           [-9.197e-07 -1.425e-07  2.120e-06  1.362e-05]]
    nfev: 10754


In [17]:
prior21 = [70, -0.55, 1]

results_pade21 = minimize(lkl_pade21,prior21,args=(zs,dls_true), method = 'Powell', tol=10**-13,  options={'maxiter':150000})
print(results_pade21)

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 52.92522368131938
       x: [ 7.449e+01 -6.830e-01  2.309e+00]
     nit: 24
   direc: [[ 2.542e-03 -6.544e-04  5.125e-03]
           [ 1.812e-01 -2.041e-02  1.320e-01]
           [ 1.825e-04 -1.794e-05  1.137e-04]]
    nfev: 2405
